version: '3.1'
services:
  auth_database:
      image: postgres:13.1-alpine
      restart: always
      container_name: auth_database
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DATABASE}
        PGDATA: /var/lib/postgresql/data/pgdata
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
        - nest_db_data:/var/lib/postgresql/data
volumes:
  nest_db_data:        