version: '3'
services:
  auth_backend:
    container_name: auth_backend
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - auth_db
    environment:
      DB_URL: DB_URI
      JWT_SECRET: JWT_SECRET
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  auth_db:
    image: mongo
    container_name: auth_db
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  mongodata:
